services:
    # db:
    #     image: mysql:8.0
    #     environment:
    #         MYSQL_ROOT_PASSWORD: example
    #         MYSQL_DATABASE: appdb
    #     ports:
    #         - "3306:3306"
    #     volumes:
    #         - db_data:/var/lib/mysql

    website:
        container_name: website
        build:
            context: .
            dockerfile: dockerfile-dev
        volumes:
          - ./next-project/src:/app/src
          - ./next-project/public:/app/public
        ports:
            - "80:3000"
        # depends_on:
        #     - db

volumes:
    db_data: