services:
    db:
        container_name: mysql-db
        build:
            context: .
            dockerfile: dockerfile-bd
        env_file: ./.env
        ports:
            - "3306:3306"

    website:
        container_name: website
        build:
            context: .
            dockerfile: dockerfile-prod
            args:
                NODE_ENV: production
                MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                MYSQL_DATABASE: ${MYSQL_DATABASE}
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
                NEXT_PUBLIC_ROOT_URL: ${NEXT_PUBLIC_ROOT_URL}
                DATABASE_HOST: ${DATABASE_HOST}
                DATABASE_USER: ${DATABASE_USER}
                DATABASE_PASSWORD: ${DATABASE_PASSWORD}
                DATABASE_NAME: ${DATABASE_NAME}
                DATABASE_PORT: ${DATABASE_PORT}
                #WATCHPACK_POLLING: true
        ports:
            - "3001:3000"
        env_file: .env
        depends_on:
            - db
        # volumes:
        #   - ./next-project/src/app:/app/src/app