services:
    db:
        container_name: mysql-db
        build:
            context: .
            dockerfile: dockerfile-bd
        env_file: ./.env
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmysecretpassword"]
          interval: 5s
          timeout: 10s
          retries: 5
        ports:
            - "3306:3306"

    website:
        container_name: website
        build:
            context: .
            dockerfile: dockerfile-dev
        ports:
            - "80:3000"
        env_file: ./.env
        depends_on:
            - db